name: Renovate
on:
  schedule:
    - cron: '0 5 * * 1' # Run every Monday at 5am UTC
  workflow_dispatch: # Allow manual triggering

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Renovate
        uses: renovatebot/github-action@v41
        with:
          configurationFile: '.github/renovate.json'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
